name: gitpod-ws-build

on:
  push:
    paths:
      - ".gitpod.Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: DOCKER_BUILDKIT=1 docker build --file .gitpod.Dockerfile .